# Generated by Django 5.0.2 on 2024-02-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='recipe'),
        ),
    ]
